[phases.setup]
aptPkgs = ["yarn-4_x"]

[phases.install]
cmds = [
    "corepack enable"
    "corepack prepare yarn@4.9.1 --activate"
    "yarn install"
    ]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn dev"
