[phases.setup]
aptPkgs = ["corepack"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare yarn@stable --activate",
  "yarn install"
]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn dev"

